enum LocalStorageKey {
  lastTimeWatchedWhatsappRewarded,
  lastTimeWatchedChatRewarded,
  emailPasswordAuthData,
  lastSendEmailTime,
  whatsappTokenData,
  lastKnowLocation,
  facebookAuthData,
  googleAuthData,
  lastLogoutTime,
  appleAuthData,
  videosCached,
  mockedPost,
  firstOpen,
  adsData,
}
