enum LocalStorageKey {
  lastTimeWatchedARewarded,
  emailPasswordAuthData,
  lastSendEmailTime,
  whatsappTokenData,
  lastKnowLocation,
  facebookAuthData,
  googleAuthData,
  lastLogoutTime,
  appleAuthData,
  videosCached,
  mockedPost,
  firstOpen,
  adsData,
}
