// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String messagingSenderId = String.fromEnvironment('FIREBASE_OPTIONS_MESSAGING_SENDER_ID');
  static const String projectId = String.fromEnvironment('FIREBASE_OPTIONS_PROJECT_ID');

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_OPTIONS_ANDROID_API_KEY'),
    appId: String.fromEnvironment('FIREBASE_OPTIONS_ANDROID_APP_ID'),
    databaseURL: 'https://$projectId.firebaseio.com',
    storageBucket: '$projectId.appspot.com',
    messagingSenderId: messagingSenderId,
    projectId: '$projectId',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    androidClientId: String.fromEnvironment('FIREBASE_OPTIONS_IOS_ANDROID_CLIENT_ID'),
    iosClientId: String.fromEnvironment('FIREBASE_OPTIONS_IOS_IOS_CLIENT_ID'),
    apiKey: String.fromEnvironment('FIREBASE_OPTIONS_IOS_API_KEY'),
    appId: String.fromEnvironment('FIREBASE_OPTIONS_IOS_APP_ID'),
    databaseURL: 'https://$projectId.firebaseio.com',
    iosBundleId: 'com.anjasolutions.tiutiuapp',
    storageBucket: '$projectId.appspot.com',
    messagingSenderId: messagingSenderId,
    projectId: '$projectId',
  );
}
