// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9SWKqAIAZ0UvUGW8p8jtkhf4_gBzFKo',
    appId: '1:791022711249:android:c455c3e55aa03aa83170f0',
    messagingSenderId: '791022711249',
    projectId: 'tiutiu-5cd14',
    databaseURL: 'https://tiutiu-5cd14.firebaseio.com',
    storageBucket: 'tiutiu-5cd14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkWxBe5Mvka6c8QFvjAl2JABvegobovT8',
    appId: '1:791022711249:ios:30fcded7e40e01623170f0',
    messagingSenderId: '791022711249',
    projectId: 'tiutiu-5cd14',
    databaseURL: 'https://tiutiu-5cd14.firebaseio.com',
    storageBucket: 'tiutiu-5cd14.appspot.com',
    androidClientId:
        '791022711249-4tcgfbn19l5k6cf8t2qblh0t66lon5d6.apps.googleusercontent.com',
    iosClientId:
        '791022711249-e7i7f4re6hrg5hamqcqdebrsjmeqs2sa.apps.googleusercontent.com',
    iosBundleId: 'com.anjasolutions.tiutiuapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb9Crkhdh9JH5xojBcqoUWAtXE2lpfk_k',
    appId: '1:791022711249:web:4f80e0be994bd54b3170f0',
    messagingSenderId: '791022711249',
    projectId: 'tiutiu-5cd14',
    authDomain: 'tiutiu-5cd14.firebaseapp.com',
    databaseURL: 'https://tiutiu-5cd14.firebaseio.com',
    storageBucket: 'tiutiu-5cd14.appspot.com',
    measurementId: 'G-T2HQWDQDPX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkWxBe5Mvka6c8QFvjAl2JABvegobovT8',
    appId: '1:791022711249:ios:c91b574d1187a6dc3170f0',
    messagingSenderId: '791022711249',
    projectId: 'tiutiu-5cd14',
    databaseURL: 'https://tiutiu-5cd14.firebaseio.com',
    storageBucket: 'tiutiu-5cd14.appspot.com',
    androidClientId: '791022711249-4tcgfbn19l5k6cf8t2qblh0t66lon5d6.apps.googleusercontent.com',
    iosClientId: '791022711249-jva0r9f0eddfo4skv18c0i1e26clq7pd.apps.googleusercontent.com',
    iosBundleId: 'com.anjasolutions.tiutiu',
  );

}