enum EndpointNames {
  pathToSystemProperties,
  userAvatarStoragePath,
  pathToPostDennounces,
  pathToPostDennounce,
  pathToSupportUsData,
  feedbackStoragePath,
  postsStoragePath,
  pathToFavorites,
  pathToFeedbacks,
  pathToFeedback,
  pathToPosts,
  pathToUsers,
  pathToUser,
  pathToPost,
}
